### PR TITLE
pop.w and push.w messages

### PR DESCRIPTION
**Pull request by roviedof**
Hi guys,

About the "pop.w" and "push.w" assembler error messages that you mention earlier.

Cortex M3/4 instruction set does not supports a ".w" condition on POP / PUSH instructions.
http://infocenter.arm.com/help/topic/com.arm.doc.dui0552a/BABIAJHJ.html
http://infocenter.arm.com/help/topic/com.arm.doc.dui0552a/BABEHFEF.html

I deleted all the ".w" on the .S files, and now it can be compiled.
I am using Arduino Due to test. I have just ran the simple vectors test, and it runs OK.

Thank you.

Renato O.

### CODE REVIEW

**Comment by iwanders** [comment]
Hey @roviedof , that's great news!

Is this actually supposed to be a PR? Or is it more a message / solution to the `.w` issue I mentioned in the readme?

I don't see any commits that address the `.w` change and the PR appears to be merging the `public` branch into my `arduino` branch. (And the diff is like impossible to digest because of it :D)

Please let me know, if the `.w` can just be cleaned up, that should be doable with a more minimal diff. I can put up a branch for that if you can test the final version before we merge that that'd be appreciated.

**Comment by roviedof** [comment]
Hi @iwanders,
It is a message/solution to the .w issue you mentioned in the readme.
It was an easy cleanup but I have not tested everything.
I can do the testing in Arduino Due, just let me know which sketches should I run and which information should I upload back here.
Thank you.

**Comment by iwanders** [comment]
Ok, I did some reading, but I don't think it's actually valid to just drop this `.w` suffix.

> The `.w` suffix to `.inst` is to indicate that the value should be handled as a wide 32 bit instruction (as opposed to a narrow 16 bit one), which only makes sense in Thumb mode.

From [this stackoverflow](https://stackoverflow.com/a/56237617), so just dropping the `.w` suffix means we now pop a 16 bit value instead of a 32 bit value?

It may compile and the test vectors may pass, but that does not provide me with enough confidence that this is a proper fix and works in ALL cases.

I really appreciate you filing the PR, but I feel like fixing it this way is risky, especially without full understanding of what happens at the assembly level. I'm closing this PR for now.

**Comment by roviedof** [comment]
I agree. Thank you.

**Pull request closed without merging**
